server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: java
    url: jdbc:mysql://localhost:3306/healthcare
    username: java
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true
    show-sql: true
